Fix broken integration test on Ruby 3.2 due to File.exists?
The `File.exists?` method has long been deprecated. In Ruby 3.2 it was
finally removed. This caused one of GLI's integration tests to fail on
Ruby 3.2:

```
  1) Error:
GLIPoweredAppTest#test_doc_generation:
NoMethodError: undefined method `exists?' for File:Class
    /Users/mbrictson/Code/davetron5000/gli/test/integration/gli_powered_app_test.rb:39:in `test_doc_generation'
```

Fix by replacing `File.exists?` with `File.exist?`.