Fixed _doc command
```
$ GLI_DEBUG=true bundle exec ticket_to_mail _doc
error: undefined method `exe_name' for nil:NilClass
/home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/commands/rdoc_document_listener.rb:23:in `program_desc': undefined method `exe_name' for nil:NilClass (NoMethodError)
        from /home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/commands/doc.rb:37:in `document'
        from /home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/commands/doc.rb:26:in `block in initialize'
        from /home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /home/jan/.gem/ruby/1.9.1/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from /home/jan/Private/VRT/Projects/ticket_to_mail/bin/ticket_to_mail:8:in `<top (required)>'
        from /home/jan/.gem/ruby/1.9.1/bin/ticket_to_mail:23:in `load'
        from /home/jan/.gem/ruby/1.9.1/bin/ticket_to_mail:23:in `<main>'
```